.github/workflows/test.yml, cypress/integration/basic.spec.js, package-lock.json, package.json, src/components/MoodLogList.jsx, src/components/WeekMoodGraph.css, src/components/WeekMoodGraph.jsx, src/components/WeekSummary.jsx, src/firebase.ts, src/helpers.ts, src/pages/Summary.css, src/pages/Summary.jsx, src/useCallbackRef.js
Includes:
- The graph (of course)
- Scroll matching between graph and list
=> Add graph to week view

.github/workflows/test.yml, .gitignore, .nycrc, cypress/plugins/index.js, cypress/support/index.js, package-lock.json, package.json, sonar-project.properties
=> Add Code Coverage and SonarCloud

src/components/Journal/JournalComponents.css
This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/nkalupahana/moody/file/main/src/components/Journal/JournalComponents.css).
=> Apply fixes from CodeFactor

cypress/integration/basic.spec.js, src/components/Journal/JournalComponents.css, src/components/Journal/WriteJournal.jsx
This PR removes the IonTextarea from WriteJournal. Don't need it anymore :)
Testing required:
=> [backlog] Remove IonTextarea from WriteJournal

src/pages/Summary.css
Fixes #29!
This requires side effects testing on:
=> Fix scroll animations on iOS app

.gitignore, firebase.json, ios/App/App/AppDelegate.swift, ios/App/App/Info.plist, ios/App/moody.entitlements, public/.well-known/apple-app-site-association
=> Handoff between iOS and web!

.github/workflows/firebase-hosting-pull-request.yml, src/components/Journal/JournalComponents.css, src/pages/Container.css
Fix #35!
Comprehensive visual tests needed on:
=> Nicer containering, especially on FinishJournal

cypress/integration/basic.spec.js, src/App.tsx, src/components/EndSpacer.tsx, src/components/Journal/FinishJournal.jsx, src/components/Journal/Negative5.tsx, src/pages/Container.css, src/pages/GapFund.tsx, src/pages/Journal.tsx
Warning added! Man, this was tough to make. Closes #33 
Requires finalization testing on:
=> Warning on -5

package-lock.json, package.json, src/helpers.tsx
=> [bugfix] better toast positioning

src/pages/Login.tsx, src/pages/Summary.css, src/pages/Summary.jsx
This is really a bug fix. Also closes #55
=> Space menu, and add flow guards to Login

functions/.gitignore, src/components/Review/PromptWeekInReview.tsx, src/pages/WeekInReview.tsx
=> WIR Anti-Forgery

cypress/integration/basic.spec.js, database.rules.json, firebase.json, functions/package-lock.json, functions/package.json, functions/src/index.ts, package-lock.json, src/App.tsx, src/components/Journal/FinishJournal.jsx, src/components/Review/PromptWeekInReview.tsx, src/components/Review/Surveyer.tsx, src/components/Settings/ChangePassphrase.tsx, src/components/Settings/PDP.css, src/components/Settings/PDP.tsx, src/components/Settings/RemovePassphrase.tsx, src/components/Settings/SetPassphrase.tsx, src/components/Settings/SettingsBox.tsx, src/components/Settings/UnlockCmp.tsx, src/components/Summary/Week/WeekSummary.tsx, src/db.ts, src/firebase.ts, src/helpers.tsx, src/lifecycle.ts, src/pages/GapFund.tsx, src/pages/Login.tsx, src/pages/RSummary.tsx, src/pages/Settings.tsx, src/pages/Summary.jsx, src/pages/Unlock.tsx, storage.rules
=> Enable PDP

src/components/Settings/NotificationEditor.jsx, src/pages/Notifications.tsx
=> Less flashing on notifications screen

src/components/Journal/JournalComponents.css, src/components/Login/MarketingBox.css, src/components/Login/MarketingBox.tsx, src/components/Settings/SettingsBox.tsx, src/pages/Login.css, src/pages/Login.tsx, src/pages/Notifications.tsx
Closes #54 -- and with this, MVP is ready to go :)
=> Onboarding!

functions/src/index.ts
=> Added rate limiting, and cleaned up preflight

cypress/e2e/basic.cy.js, src/App.tsx, src/components/Review/WeekInReviewReview.tsx, src/components/Summary/Month/MonthCalendar.css, src/components/Summary/Week/WeekMoodGraph.css, src/components/Summary/Week/WeekSummary.tsx, src/helpers.tsx, src/pages/Container.css, src/pages/GetHelp.tsx, src/pages/Summary.css, src/pages/Summary.jsx, src/pages/SurveyResults.tsx, src/screeners/spf.tsx
Closes #57 , and moves closer to fixing #41
=> Survey page, and some responsive styling

README.md, cypress/e2e/basic.cy.js, package-lock.json, package.json, src/App.tsx, src/components/Journal/FinishJournal.jsx, src/pages/Container.css, src/pages/GapFund.tsx, src/pages/Journal.tsx, src/pages/Login.tsx, src/pages/Notifications.tsx
=> Add basic route transitions

src/components/Summary/ImageCarousel.jsx, src/components/Summary/Month/MonthMoodLogList.jsx, src/components/Summary/Month/MonthSummary.tsx, src/components/Summary/MoodLogCard.jsx, src/components/Summary/MoodLogList.tsx, src/components/Summary/Week/WeekMoodGraph.css, src/components/Summary/Week/WeekMoodGraph.jsx, src/components/Summary/Week/WeekMoodLogList.jsx, src/components/Summary/Week/WeekSummary.tsx, src/pages/Summary.css, src/pages/Summary.jsx
=> Fix Flickity Fullscreen, and Scroll Bugs on WeekSummary

src/components/Review/WeekInReviewReview.tsx, src/helpers.tsx, src/pages/SurveyResults.tsx
=> Polish SurveyResults

android/app/src/main/assets/capacitor.config.json, capacitor.config.ts, functions/src/index.ts, ios/App/App/capacitor.config.json, src/App.tsx, src/components/Journal/WriteJournal.jsx, src/components/KeyboardSpacer.tsx, src/pages/Login.tsx, src/pages/Notifications.tsx
=> Little fixes for VP

cypress/e2e/basic.cy.js, src/components/Journal/FinishJournal.jsx, src/components/Journal/WriteJournal.jsx, src/firebase.ts, src/pages/RSummary.tsx
=> Add autosave!

src/components/Review/WeekInReviewReview.tsx, src/pages/WeekInReview.css
=> Move WIR arrows up a bit

cypress/e2e/basic.cy.js, src/pages/Login.tsx
Fixes #117 
The only needed test for this is Cypress.
=> Remove Anonymous button

src/components/Review/WeekInReviewInitial.tsx
Fixes #116 
Just needs a code review and visual check!
=> Add PDP warning

functions/package-lock.json, functions/package.json, functions/src/index.ts
This is used for the internal BI dashboard! Everything looks good to go.
=> BI data written to BigQuery

src/components/Settings/NotificationEditor.css, src/components/Summary/Week/WeekSummary.tsx, src/pages/Container.css, src/pages/Notifications.tsx
=> Quick fixes for iPad

cypress/e2e/basic.cy.js, package-lock.json, package.json, src/components/Summary/Month/MonthCalendar.jsx, src/components/Summary/Month/MonthMoodLogList.jsx, src/components/Summary/Month/MonthSummary.tsx, src/components/Summary/MoodLogCard.jsx, src/components/Summary/MoodLogList.tsx, src/components/Summary/SearchAndFilter.tsx, src/components/Summary/Week/WeekMoodLogList.jsx, src/components/Summary/Week/WeekSummary.tsx, src/helpers.tsx, src/pages/Summary.css, src/pages/Summary.jsx, src/pages/Unlock.tsx, src/theme/variables.css
=> Search and Filter!

functions/src/index.ts
=> Added email loading to functions

src/components/Review/SurveyGraph.tsx, src/components/Review/WeekInReviewReview.tsx, src/data.tsx, src/helpers.tsx, src/screeners/dass.tsx, src/screeners/screener.ts, src/screeners/spf.tsx
Fixes #139 
Fixes #133 
Fixes #134
=> WIR Bug Fixes!

functions/src/index.ts
=> Gap fund count now loaded into BigQuery

src/components/Journal/FinishJournal.jsx
=> Fix image edit issue

cypress/e2e/basic.cy.js, functions/src/index.ts, src/pages/Container.css, src/pages/Donate.tsx, src/pages/Login.tsx, src/pages/Settings.tsx
=> Account deletion

functions/src/index.ts
=> Increase character limit

docs/_includes/header.html, docs/_layouts/default.html, docs/site.webmanifest, public/site.webmanifest
=> Manifest & a11y issues on landing

android/app/src/main/java/app/getbaseline/baseline/MainActivity.java, android/app/src/main/res/values-sw600dp/bools.xml, android/app/src/main/res/values/bools.xml, src/pages/Summary.jsx
=> Short Screen Bug Fixing

package-lock.json, package.json, src/App.tsx
=> Add mobile on web lockup

android/app/build.gradle, docs/_includes/header.html, docs/_sass/layout.scss, ios/App/App/Info.plist, src/pages/Login.tsx
=> Bump version, and add legal links

ios/App/App/Info.plist, src/firebase.ts
Fix #168 (see checklist there)
=> Change auth domain to baseline

public/index.html, src/components/Review/WeekInReviewReview.tsx, src/data.tsx, src/pages/Container.css, src/pages/Login.tsx, src/pages/Notifications.tsx, src/pages/SurveyResults.tsx, src/screeners/dass.tsx, src/screeners/spf.tsx
Fixes #141 
Fixes #115 
This adds:
- Verbiage changes
- Android WebView fixes for dark mode
- Loader for FCM
=> WIR-related Verbiage and FCM Loader

src/helpers.tsx
=> New colors for ends of spectrum

android/app/build.gradle, ios/App/App/Info.plist, src/components/Review/WeekInReviewReview.tsx
Also bumps version since we're on a new release cycle!
=> Set wir timestamp on finish surveys

package-lock.json
=> Fix slider errors at -5/5

src/components/Settings/NotificationEditor.jsx
Fixes [DEV-9 (Adding multiple notifications at the same time leads to duplications)](https://getbaseline.atlassian.net/jira/software/projects/DEV/boards/1?selectedIssue=DEV-9)
Things to test:
- Adding notification on same time as another
- Changing notification time (normal)
- Changing notification time to time another notification is already on
=> Cancel on both old and new time

android/.gitignore, src/App.tsx, src/pages/Notifications.tsx
=> [DEV-11] Update app links to point to landing page

cypress/component/messages.cy.js, cypress/e2e/basic.cy.js, functions/src/index.ts, src/components/Review/WeekInReviewInitial.tsx, src/data.tsx, src/pages/WeekInReview.tsx, src/screeners/ede_qs.tsx, src/screeners/wast.tsx
=> [DEV-19] Add WAST for Domestic Violence & Abuse Screening

functions/src/index.ts
=> Add monitoring test function

functions/src/index.ts
=> Fix BI Date Timezones

functions/src/index.ts
=> Increase memory limit on Cloud Function

package-lock.json, package.json
=> Fix android notification crashes

cypress/e2e/basic.cy.js, src/components/Review/PromptWeekInReview.css, src/components/Review/PromptWeekInReview.tsx, src/pages/Settings.tsx
Closes #188 and DEV-26 (internal)
=> Add WIR Skip Feature

android/app/build.gradle, android/app/src/main/java/app/getbaseline/baseline/MainActivity.java
=> Add WebView upgrade warning

functions/src/index.ts, src/helpers.tsx, src/pages/Login.tsx
=> Add more info to login (sign in with apple errors)

src/components/Summary/MoodLogCard.css, src/components/Summary/MoodLogCard.jsx, src/helpers.tsx, src/theme/variables.css
=> Add color markers to MoodLogCard

.github/workflows/nightly-test.yml, package.json
=> Add Nightly Tests

docs/_layouts/default.html
=> Set up deep links on website

docs/_pages/privacypolicy.md, docs/_pages/terms.md
=> Now incorporated!

android/app/build.gradle, android/build.gradle, ios/App/App.xcodeproj/project.pbxproj, ios/App/Podfile
=> Add Crashlytics

functions/src/index.ts
=> Merge update and database object

cypress/e2e/basic.cy.js, src/App.tsx, src/components/Review/WeekInReviewReview.tsx, src/pages/LastWeekInReview.tsx, src/pages/SurveyResults.tsx, src/pages/WeekInReview.tsx
=> View last Week In Review

.github/workflows/firebase-hosting-main.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/nightly-test.yml, .github/workflows/test.yml, docs/_includes/footer.html, docs/_sass/base.scss, sonar-project.properties, src/components/Journal/FinishJournal.jsx, src/components/Settings/NotificationEditor.jsx, src/firebase.ts, src/helpers.tsx, src/pages/Notifications.tsx, src/pages/WeekInReview.tsx
=> Fix non-cognitive complexity SonarCloud issues

android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, ios/App/Podfile, package-lock.json, package.json, src/components/Journal/FinishJournal.jsx
=> Ask for reviews from users

.github/workflows/test.yml, cypress/e2e/e2e.cy.js, helpers/marketingData.js, src/components/Summary/Month/MonthCalendar.jsx, src/components/Summary/MoodLogCard.jsx, src/components/Summary/MoodLogList.tsx, src/components/Summary/Week/WeekMoodGraph.jsx, src/helpers.tsx, src/pages/Settings.tsx
=> Fix marketing script, ISO date prod fix, and add colorblind mode

.github/workflows/backend.yml, .github/workflows/test.yml, backend/.gcloudignore, backend/.gitignore, backend/Dockerfile, backend/package-lock.json, backend/package.json, backend/src/accounts.ts, backend/src/gap.ts, backend/src/helpers.ts, backend/src/index.ts, backend/src/main.ts, backend/src/pdp.ts, backend/tsconfig.json, functions/src/index.ts, sonar-project.properties, src/components/Journal/FinishJournal.jsx, src/components/Review/PromptWeekInReview.tsx, src/components/Settings/ChangePassphrase.tsx, src/components/Settings/RemovePassphrase.tsx, src/components/Settings/SetPassphrase.tsx, src/components/Summary/ImageCarousel.jsx, src/helpers.tsx, src/pages/GapFund.tsx, src/pages/Login.tsx
=> Migrate to Cloud Run Backend

src/components/Summary/MoodLogList.tsx, src/components/Summary/Week/WeekMoodGraph.jsx
=> Fix issues on Summary view (timezones, graph rendering on mini-desktop)

package-lock.json, package.json, src/components/Journal/FinishJournal.jsx
=> Add confetti for +5

.github/workflows/nightly-test.yml, .github/workflows/test.yml
=> Smoke testing for backend

docs/_pages/privacypolicy.md, src/pages/Donate.tsx
=> Update donate page

.github/workflows/backend.yml, backend/.gitignore, backend/package-lock.json, backend/package.json, backend/src/gap.ts, backend/src/index.ts
=> Email Notifications for Gap Fund Submissions

src/pages/GapFund.tsx
=> Add username and detail notes for gap fund

cypress/component/messages.cy.js, src/components/Review/BaselineDescription.tsx, src/components/Review/WeekInReviewReview.tsx, src/data.tsx, src/helpers.tsx, src/pages/SurveyResults.tsx
This should actually be DEV-39; oops.
=> New baseline text, and new formula that factors in non-average logs

.github/workflows/internal.yml, .github/workflows/test.yml, backend/main.tf, backend/package.json, scheduled-services/main.tf, scheduled-services/package-lock.json, scheduled-services/package.json
=> Add tf for backend, and automate smoke testing and deployment for internal

src/firebase.ts
=> Just delete token, and let BI cleanup handle token removal from database

scheduled-services/src/index.ts, scheduled-services/src/messaging.ts
=> Add token cleanup endpoint and integrate (dry)

backend/src/accounts.ts, backend/src/helpers.ts, database.rules.json, src/firebase.ts, src/pages/Login.tsx, src/pages/Summary.jsx
=> Add offline sync and future-proof data return to getOrCreateKeys

scheduled-services/main.tf, scheduled-services/src/index.ts, scheduled-services/src/messaging.ts
=> DEV-68 & DEV-69 Infrastructure

scheduled-services/main.tf, scheduled-services/src/index.ts, scheduled-services/src/messaging.ts
=> Infra for DEV-68 and -69

scheduled-services/src/messaging.ts
=> Clean up logging and enable in prod

backend/main.tf, backend/package-lock.json, backend/package.json, backend/src/main.ts, functions/src/index.ts, scheduled-services/main.tf, scheduled-services/src/index.ts, scheduled-services/src/messaging.ts
=> Infra to push to PubSub on mood log to clean stuff up

src/components/Journal/JournalComponents.css, src/components/Review/Surveyer.tsx, src/pages/WeekInReview.css, src/screeners/cage_aid.tsx, src/screeners/dass.tsx, src/screeners/ede_qs.tsx, src/screeners/harm.tsx, src/screeners/screener.ts, src/screeners/spf.tsx, src/screeners/wast.tsx
=> Undo functionality for WIR

src/App.tsx, src/pages/Container.css, src/pages/Login.css, src/pages/Login.tsx, src/pages/Preloader.tsx
=> Make login page nicer

.github/workflows/test.yml, android/app/build.gradle, cypress/e2e/e2e.cy.js, ios/App/App.xcodeproj/project.pbxproj, package-lock.json, package.json
=> Stabilize Frontend Tests

backend/src/main.ts, helpers/marketingData.js
=> [PROD-19] Switch backend to non-locale function

backend/main.tf, backend/package-lock.json, backend/package.json, backend/src/analytics.ts, backend/src/helpers.ts, backend/src/index.ts
=> Add analytics endpoint to backend

docs/_layouts/default.html, package-lock.json, package.json, src/helpers.tsx, src/murmurhash3_gc.js, src/pages/Login.tsx
=> Add conversion tracking to baseline and landing page

android/app/src/main/AndroidManifest.xml, backend/src/accounts.ts, backend/src/analytics.ts, ios/App/App/AppDelegate.swift, ios/App/App/Info.plist, ios/App/Podfile, src/App.tsx, src/components/Onboarding/OnboardingNotifications.tsx
=> Remove Dynamic Links

scheduled-services/main.tf
=> Allow datastore view for scheduled-services

.github/workflows/firebase-hosting-pull-request.yml, scheduled-services/src/bi.ts
=> Put Firestore conversion data into BigQuery

scheduled-services/src/bi.ts
=> Add timestamp to length BI data

src/components/Settings/NotificationEditor.css
=> Round corners in NotificationEditor

src/firebase.ts
=> Don't remove notifications on sign out

backend/src/granite.ts, backend/src/index.ts, src/App.tsx, src/components/Settings/GraniteCallback.tsx, src/components/Settings/GraniteLink.tsx, src/pages/Settings.tsx
=> Add web granite login

firebase.json
=> Fix clickjacking vulnerabilities

scheduled-services/src/bi.ts
=> Add BI loading for Granite data

src/components/Onboarding/OnboardingHowToJournal.tsx
in journal example replaced "carrie" with "lucia"
=> removed carrie replaced with lucia

cypress/e2e/e2e.cy.js, src/components/Summary/Month/MonthMoodLogList.jsx, src/components/Summary/SearchAndFilter.tsx, src/components/Summary/Week/WeekSummary.tsx, src/pages/Summary.css
=> Add entry count to SearchAndFilter

.github/workflows/firebase-hosting-main.yml, .github/workflows/firebase-hosting-pull-request.yml, .github/workflows/test.yml, package.json, postbuild, prebuild, src/components/Journal/WriteJournal.jsx, src/index.tsx
=> Add Sentry source maps to CI pipeline

docs/_pages/privacypolicy.md, ios/App/App.xcodeproj/project.pbxproj, ios/App/App/AppDelegate.swift
=> Added Adjust to iOS

android/app/build.gradle, backend/src/gap.ts, cypress/e2e/e2e.cy.js, ios/App/App.xcodeproj/project.pbxproj, package-lock.json, package.json, src/helpers.tsx, src/pages/GapFund.tsx
=> Change requirements for Gap Fund

README.md, cypress/e2e/e2e.cy.js, ios/App/App.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, package-lock.json, package.json, src/components/Journal/FinishJournal.jsx, src/components/Journal/JournalComponents.css, src/theme/variables.css
=> Add product tour to FinishJournal 

backend/src/accounts.ts, src/components/Onboarding/OnboardingNotifications.tsx, src/components/Review/PromptWeekInReview.tsx, src/pages/Login.tsx
Adds new fields to /user/info - sets the platform to true if the user logs in through said platform. Ex, if user logs in with web, /user/info/web will be set to true.
=> Add platform to accounts/sync

android/app/capacitor.build.gradle, android/app/src/main/assets/capacitor.plugins.json, android/capacitor.settings.gradle, helpers/marketingData.js, ios/App/App/Info.plist, ios/App/Podfile, ios/App/Podfile.lock, package-lock.json, package.json, src/components/Journal/FinishJournal.jsx, src/components/Onboarding/OnboardingHowToJournal.tsx, src/firebase.ts, src/pages/Login.tsx
=> Enable GA4 for Android

src/screeners/cage_aid.tsx, src/screeners/ede_qs.tsx, src/screeners/harm.tsx
=> Clean Up Week In Review

backend/src/accounts.ts, ios/App/Podfile.lock, package-lock.json, package.json, src/pages/Login.tsx
Apple sign in on:
Google sign in on:
=> Fix Apple + Passphrase bug and add Native CloudKit for iOS

android/app/src/main/java/app/getbaseline/baseline/MainActivity.java
=> Disable text resizing on Android

src/App.tsx, src/components/EndSpacer.tsx, src/components/Journal/FinishJournal.jsx, src/components/Journal/WriteJournal.jsx, src/components/MyData/ExportData.tsx, src/components/Onboarding/OnboardingHowToJournal.tsx, src/components/Review/WeekInReviewInitial.tsx, src/components/Review/WeekInReviewReview.tsx, src/components/Settings/ChangePassphrase.tsx, src/components/Settings/GraniteCallback.tsx, src/components/Settings/PDP.tsx, src/components/Settings/RemovePassphrase.tsx, src/components/Settings/SetPassphrase.tsx, src/components/Settings/UnlockCmp.tsx, src/components/Summary/MoodLogList.tsx, src/data.tsx, src/pages/GapFund.tsx, src/pages/Login.tsx, src/pages/Notifications.tsx, src/pages/Preloader.tsx, src/pages/Settings.tsx, src/pages/SurveyResults.tsx, src/screeners/wast.tsx, src/theme/variables.css
=> Remove <br />s used for spacing instead of text layout

src/components/Journal/WriteJournal.jsx, src/pages/Journal.tsx
=> Fix autosave not showing up in /journal/finish

scheduled-services/package-lock.json, scheduled-services/package.json, scheduled-services/src/messaging.ts
=> Chunk messages by 500 to avoid errors

ios/App/App.xcodeproj/project.pbxproj, ios/App/App.xcodeproj/xcshareddata/xcschemes/App.xcscheme, ios/App/App/AppDelegate.swift, ios/App/App/Info.plist, ios/App/GoogleService-Info.plist, ios/App/Podfile, ios/App/Podfile.lock, src/components/Onboarding/OnboardingHowToJournal.tsx, src/pages/Login.tsx
=> Add GA to iOS

backend/src/main.ts, cypress/e2e/e2e.cy.js, src/components/Journal/FinishJournal.jsx, src/components/Journal/WriteJournal.jsx, src/components/Summary/MoodLogCard.css, src/components/Summary/MoodLogCard.tsx, src/components/Summary/MoodLogList.tsx, src/components/graphs/helpers.tsx, src/helpers.tsx, src/pages/Journal.tsx
=> Typo Editing

backend/src/index.ts, backend/src/main.ts, backend/src/spotify.ts
=> Add Spotify search to backend

cypress/e2e/e2e.cy.js, src/components/Journal/SearchSpotify.css, src/components/Journal/SearchSpotify.tsx, src/components/MyData/constants.tsx, src/components/Summary/MoodLogCard.tsx
=> Spotify fixes for production rollout

scheduled-services/Dockerfile, scheduled-services/main.tf
=> Add new PubSub connection and ffmpeg (scheduled-services, voice journaling)

android/app/src/main/AndroidManifest.xml, cypress/e2e/e2e.cy.js, ios/App/App/Info.plist, src/components/Journal/FinishJournal.jsx, src/components/Journal/JournalComponents.css, src/components/Journal/RecordJournal.css, src/components/Journal/RecordJournal.tsx, src/components/Journal/StartJournal.jsx, src/components/Journal/StartJournal.tsx, src/components/Journal/WriteJournal.tsx, src/components/Summary/AudioViewer.tsx, src/components/Summary/MoodLogCard.css, src/components/Summary/MoodLogCard.tsx, src/db.ts, src/helpers.tsx, src/pages/Journal.tsx
=> [Audio Journaling] Frontend v1

scheduled-services/main.tf, scheduled-services/src/audio.ts, scheduled-services/src/index.ts
=> [Audio Journaling] Add dead letter queue + other backend improvements

package-lock.json
=> Bump @capacitor packages

backend/src/main.ts
=> [Audio Journaling] Backend v2 Fixes

capacitor.config.ts, cypress/e2e/e2e.cy.js, package-lock.json, package.json, src/App.tsx, src/components/Journal/JournalComponents.css, src/components/Journal/WriteJournal.tsx, src/components/KeyboardSpacer.tsx, src/pages/Container.css, src/pages/Journal.tsx
=> Auto-scroll and other WriteJournal Fixes

backend/src/main.ts
=> Add backend changes to allow summary backlogging

android/app/build.gradle, cypress/e2e/e2e.cy.js, ios/App/App.xcodeproj/project.pbxproj, package-lock.json, package.json, src/components/Journal/FinishJournal.jsx, src/components/Journal/StartJournal.tsx, src/components/Summary/Month/MonthCalendar.jsx, src/components/Summary/MoodLogCard.tsx, src/components/Summary/MoodLogList.tsx, src/data.tsx, src/db.ts, src/helpers.tsx, src/pages/Journal.tsx, src/pages/Settings.tsx, src/pages/Summary.jsx
=> Add system for journaling on day before

backend/src/accounts.ts
=> Fix iCloud delete-and-recreate keys bug

src/components/Summary/Month/MonthCalendar.jsx
=> Allow click on more places on MonthCalendar

src/components/Onboarding/OnboardingNotifications.tsx, src/components/Streaks/StreakDialog.tsx, src/pages/Summary.jsx
=> Clean up Firebase messaging and dialog persistence

patches/@capacitor-firebase+authentication+6.0.0.patch
Oh boy.
Attempt to resolve #401 and support ticket
=> Add scopes when requesting access token

backend/Dockerfile
This should fix HEIC support by installing `libvips` directly.
=> Fix HEIC Support

.github/workflows/test.yml, android/app/build.gradle
=> Build and sign AABs on main automatically

src/App.tsx, src/pages/WrappedSummary.tsx
=> Error Boundary + Reload on broken IndexedDB

backend/src/index.ts, backend/src/streak.ts
=> [Widgets] Add streak calculation to backend

backend/src/streak.ts
=> [Widget] Backend: add danger levels

cypress/e2e/e2e.cy.js, src/components/Journal/FinishJournal.jsx, src/components/Journal/InfoBadge.tsx, src/components/Journal/StartJournal.tsx, src/components/Onboarding/OnboardingHowToJournal.tsx, src/pages/Settings.tsx
=> Removed prompts question and added some badges for edit/summary view

cypress/e2e/e2e.cy.js, src/components/Journal/FinishJournal.jsx, src/components/Journal/InfoBadge.tsx, src/components/Journal/StartJournal.tsx
=> Info badge for both edits and summary

backend/src/streak.ts, src/components/Streaks/helpers.ts, src/components/Summary/MoodLogList.tsx, src/pages/Summary.jsx
Gonna roll this out to start, and write tests in a future PR.
=> Support journal entries from the future

backend/src/streak.ts, cypress/e2e/e2e.cy.js, src/components/Settings/DebugButtons.tsx, src/data.tsx, src/firebase.ts, src/pages/Settings.tsx
=> Tests for journals in the future
